### ISSUE TITLE
"This field does not exist" but it does (nightly) 

### ISSUE THREAD

**Issue by schurhammer** [gleam-lang/gleam#3629]
On the nightly build I get an unknown record field error when running gig.
The same code runs fine with the stable release (1.4.1).

I get this error

```
error: Unknown record field
    ┌─ /home/julian/projects/gig/src/gig/closure.gleam:209:74
    │
209 │           let fun_type = t.FunctionType([env_type, ..var_types], fun_body.typ)
    │                                                                          ^^^^ This field does not exist

The value being accessed has this type:

    Exp

It does not have any fields.
```

gleam 1.5.0-rc1-nightly-20240915

https://github.com/schurhammer/gig
commit ce4df57eb3b16ee9f9d1407943b9ddf61dadf24c
(latest commit at time of writing)

**Comment by lpil** [comment]
Thank you

**Comment by lpil** [comment]
@giacomocavalieri said on discord:

Oh that's funny, the smallest example I could find to trigger it is this one:
```gleam
// In file `bug.gleam`
import imported

pub type Exp {
  One(field: imported.Wibble)
  Two(field: imported.Wibble)
}

fn main() {
  let exp = One(todo)
  exp.field
}

// In file `imported.gleam`
pub type Wibble
```

What's interesting is that it only happens if you use imported.Wibble, if you change it to:
```gleam
import imported.{type Wibble}

pub type Exp {
  One(field: Wibble)
  Two(field: Wibble)
}
```
The compilation error goes away

**Comment by lpil** [comment]
Git bisect has lightlighted this commit as the first with the issue

https://github.com/gleam-lang/gleam/commit/a0d7f44f2b95e194d86bda776e092825cbc7d7e4

**Comment by lpil** [comment]
I think this is the first commit with the problem, but can't see what the issue is

https://github.com/gleam-lang/gleam/commit/a0d7f44f2b95e194d86bda776e092825cbc7d7e4

**Comment by lpil** [comment]
https://github.com/gleam-lang/gleam/commit/f4e41301684a6c52fbe1ee9bd8312b309eb7abde
