### PR TITLE
Fix JavaScript names escaping a case clause

### LINKED ISSUE #6212: JavaScript code generator calls the wrong variable when a case pattern has the same name as a function
The gleam fuzzer strikes again! This program:

```gleam
fn wibble(_: Int) -> Float {
  0.0
}

pub fn main() {
  case 0 + 0 {
    wibble -> {
      echo wibble
    }
  }
  |> wibble
}

```

Crashes with this error message on the JavaScript target, but runs fine on Erlang:

```bash
$ gleam run -tjs
  Compiling app
   Compiled in 0.02s
    Running app.main
src/app.gleam:8
0
file:///app/build/dev/javascript/app/app.mjs:23
  return wibble$1(_pipe);
         ^

TypeError: wibble$1 is not a function
    at main (file:///app/build/dev/javascript/app/app.mjs:23:10)
    at file:///app/build/dev/javascript/app/gleam@@private_main_v1.18.1.mjs:2:1
    at ModuleJob.run (node:internal/modules/esm/module_job:345:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:651:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:117:5)

Node.js v22.19.0
```

This happens on gleam `v1.18.1` and nightly.

### LINKED ISSUE #6213: JavaScript code generator uses the wrong variable when a let inside a case arm shadows an outer variable
This Gleam program:

```gleam
pub fn main() {
  let m = 1
  let _ = case 0 + 0 {
    _ -> {
      let m = 99
      m
    }
  }
  echo m
}
```

Generates incorrect JavaScript. It should output 1, which it does on the Erlang target, but `m` is not shadowed correctly on the JavaScript target:
```bash
$ gleam run -terl
src/app.gleam:9
1

$ gleam run -tjs
src/app.gleam:9
99
```

This happens on gleam v1.18.1 and nightly.

### PR DESCRIPTION
**Pull request by jtdowney**
Closes #6212
Closes #6213

This is related to #5743 in that it is from when decision trees can be embedded into the parent scope without any if/else branches which create new scope for JS. I took the code largely introduced in #5746 and applied it for this case too.

Since this had popped up a few times I also went and looked for other cases and found one relating to guards. Bindings for guards are declared in outer scope.

For example, this is a problem because `b` gets declared twice:

```
----- SOURCE CODE

pub fn go(x) {
  case x {
    #(_, b) if b == 2 -> b
    #(_, b) -> b
  }
  let b = 5
  b
}

----- COMPILED JAVASCRIPT
export function go(x) {
  let b = x[1];
  if (b === 2) {
    b;
  } else {
    let b = x[1];
    b;
  }
  let b = 5;
  return b;
}
```

- [x] The changes in this PR have been discussed beforehand in an issue
- [x] The issue for this PR has been linked
- [x] Tests have been added for new behaviour
- [x] The changelog has been updated for any user-facing changes

### CODE REVIEW

**Review by lpil — APPROVED** [review]
Very nice! Super clean. Thank you again!!!
